apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: <YOUR-GIT-REPO-URL> # Add your Git repository URL
type: kubernetes.io/basic-auth
stringData:
  username: <Enter unencrypted username>
  password: <Enter unencrypted password>
